### ISSUE TITLE
Add MIT license?

### ISSUE THREAD

**Issue by ericfranz** [stanford-rc/sh_ood-apps#1]
Would you be willing to add an MIT license to this repo so that these could be reused as widely as OnDemand is? These are great examples and in particular the AuthRevProxy is a very cool solution for adding authentication to TensorBoard. For convenience, on the GitHub interface, click create a new file, type LICENSE or LICENSE.md and a "choose license" button should appear to the right of the editor.

**Comment by kcgthb** [comment]
Thanks for pointing the lack of license for this repo, that's fixed now (via bff2d7a).

We generally release our work under the GPL, partly to ensure that distributed modifications are open-sourced.

**Comment by kcgthb** [comment]
Closing #1
